Feature btn add library ft 18&ft 19
po4tovuj/project-js-18-plus pull request #31
Opened 2022-11-03 12:33 UTC by Olexandr-Sliusar

У меня не вышло получить юзер ид из фаербеса. Можешь это сделать в файле local-storage.js и потом нужно удалить статический

2022-11-03 18:43 UTC, po4tovuj requested changes

2022-11-03 18:43 UTC, po4tovuj commented on src/index.scss
> -@import 'sass/layout/header';
Навіщо ти змінив шлях?****

2022-11-03 18:43 UTC, po4tovuj commented on src/index.scss
> +// @import 'sass/layout/loader';
Нащо закоментував. Ці стилі потрібні

2022-11-03 18:43 UTC, po4tovuj commented on src/js/local-storage.js
> +});
Тут має бути let userid= ""
Якщо є юзер то записуєш айді
Якщо немає то записуєш пусту строку

2022-11-03 18:43 UTC, po4tovuj commented on src/js/homepage.js
>    refs.libraryListError.style.display = 'none';
Помилки треба не тільки ховати а і очищати

2022-11-03 18:43 UTC, po4tovuj commented on src/js/modal.js
>  const refs = getRefs();
Це зайве refs це просто об'єкт

2022-11-03 18:43 UTC, po4tovuj commented on src/js/local-storage.js
> +});
або null якщо user.uid === type number

2022-11-03 18:43 UTC, po4tovuj commented on src/js/local-storage.js
> +    if (findIndexMovie > -1) {
робиш переверку на не знайдено і пишеш renturn
а нижче робиш то що має робити якщо знайдено

2022-11-03 18:43 UTC, po4tovuj commented on src/js/local-storage.js
> +    return false;
return moviesFromLocaleStorage[listName].findIndex(
        movie => movie.id === movieId
      ) > -1

2022-11-03 18:43 UTC, po4tovuj commented on src/js/modal.js
> +  }
повернути їх назад там де вони були, не всередині функціі а як окремі сутності

2022-11-03 18:43 UTC, po4tovuj commented on src/js/my-library.js
>    console.log('should call');
видали будь-ласка

2022-11-03 18:43 UTC, po4tovuj commented on src/js/my-library.js
> -  hideLoader();
повернути назад

2022-11-03 18:43 UTC, po4tovuj commented on src/js/my-library.js
> +  hideLoader();
видалити

2022-11-04 07:26 UTC, Olexandr-Sliusar commented on src/index.scss
> -@import 'sass/layout/header';
пути поправил, лишнее удалил

2022-11-04 07:27 UTC, Olexandr-Sliusar commented on src/index.scss
> +// @import 'sass/layout/loader';
потому что файл перенес в другую папку еше по просьбе Романа

2022-11-04 07:28 UTC, Olexandr-Sliusar commented on src/js/local-storage.js
> +});
поправил, должно работать, но не проверил, так как в хедере не работают кнопки и не могу зайти на страницу лайбари

2022-11-04 07:29 UTC, Olexandr-Sliusar commented on src/js/homepage.js
>    refs.libraryListError.style.display = 'none';
вчера это обсудили на звонке, решили так оставить

2022-11-04 07:29 UTC, Olexandr-Sliusar commented on src/js/modal.js
>  const refs = getRefs();
не проверил что он используется и потому не удалял

2022-11-04 07:29 UTC, Olexandr-Sliusar commented on src/js/local-storage.js
> +    return false;
+

2022-11-04 07:33 UTC, Olexandr-Sliusar commented on src/js/modal.js
> +  }
не возвращал, так как слушатель объявляется внутри онОпен и туда же перенес эти методы. Если их вернуть туда где их создал Вадим, то будут ошибки "нет доступа". Проверил ничего не ламается, и при этом я могу удалять своих слушателей. Функции онКейДаун и ОнКликОутсайд заисимы от онКлоз и потому их тоже оставил внутри онОпен.

2022-11-04 07:33 UTC, Olexandr-Sliusar commented on src/js/my-library.js
>    console.log('should call');
+

2022-11-04 07:34 UTC, Olexandr-Sliusar commented on src/js/my-library.js
> -  hideLoader();
оставил, так как не успел, но так как там запросы в локалсторадж, то мне кажется что это не критично

2022-11-04 12:19 UTC, po4tovuj approved these changes

2022-11-04 12:20 UTC, merged